"""Complete student profile system

Revision ID: b6367fff1e63
Revises: 0a1c14db1017
Create Date: 2026-08-28 22:37:22.036552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6367fff1e63'
down_revision: Union[str, Sequence[str], None] = '0a1c14db1017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education', sa.Column('education_level', sa.String(), nullable=True))
    op.add_column('education', sa.Column('specialization', sa.String(), nullable=True))
    op.add_column('education', sa.Column('university_or_board', sa.String(), nullable=True))
    op.add_column('education', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('education', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('education', sa.Column('currently_studying', sa.Boolean(), nullable=True))
    op.add_column('education', sa.Column('percentage', sa.Float(), nullable=True))
    op.add_column('education', sa.Column('cgpa', sa.Float(), nullable=True))
    op.add_column('education', sa.Column('grading_system', sa.String(), nullable=True))
    op.drop_column('education', 'grade_or_cgpa')
    op.drop_column('education', 'start_year')
    op.drop_column('education', 'field_of_study')
    op.drop_column('education', 'graduation_year')
    op.add_column('experience', sa.Column('company_location', sa.String(), nullable=True))
    op.add_column('experience', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('experience', sa.Column('skills_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('experience', 'location')
    op.add_column('projects', sa.Column('project_type', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('currently_active', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('technologies', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('projects', sa.Column('responsibilities', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('team_size', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('project_status', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('resumes', sa.Column('is_primary', sa.Boolean(), nullable=True))
    op.add_column('resumes', sa.Column('visibility', sa.String(), nullable=True))
    op.drop_constraint(op.f('resumes_student_id_key'), 'resumes', type_='unique')
    op.add_column('student_profiles', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('career_status', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('profile_headline', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('linkedin_url', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('github_url', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('portfolio_url', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('personal_website', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('preferred_job_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('student_profiles', sa.Column('preferred_work_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('student_profiles', sa.Column('preferred_industries', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('student_profiles', sa.Column('notice_period', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('job_search_status', sa.String(), nullable=True))
    op.alter_column('student_profiles', 'work_mode',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='work_mode::jsonb')
    op.alter_column('student_profiles', 'employment_type',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='employment_type::jsonb')
    op.drop_column('student_profiles', 'preferred_job_role')
    op.drop_column('student_profiles', 'secondary_job_role')
    op.drop_column('student_profiles', 'preferred_location')
    op.add_column('student_skills', sa.Column('proficiency', sa.String(), nullable=True))
    op.add_column('student_skills', sa.Column('years_of_experience', sa.Float(), nullable=True))
    op.add_column('student_skills', sa.Column('last_used', sa.Integer(), nullable=True))
    op.add_column('student_skills', sa.Column('priority', sa.String(), nullable=True))
    op.drop_constraint(op.f('student_skills_skill_id_fkey'), 'student_skills', type_='foreignkey')
    op.drop_constraint(op.f('student_skills_student_id_fkey'), 'student_skills', type_='foreignkey')
    op.create_foreign_key(None, 'student_skills', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'student_skills', 'student_profiles', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_skills', type_='foreignkey')
    op.drop_constraint(None, 'student_skills', type_='foreignkey')
    op.create_foreign_key(op.f('student_skills_student_id_fkey'), 'student_skills', 'student_profiles', ['student_id'], ['id'])
    op.create_foreign_key(op.f('student_skills_skill_id_fkey'), 'student_skills', 'skills', ['skill_id'], ['id'])
    op.drop_column('student_skills', 'priority')
    op.drop_column('student_skills', 'last_used')
    op.drop_column('student_skills', 'years_of_experience')
    op.drop_column('student_skills', 'proficiency')
    op.add_column('student_profiles', sa.Column('preferred_location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('student_profiles', sa.Column('secondary_job_role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('student_profiles', sa.Column('preferred_job_role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('student_profiles', 'employment_type',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('student_profiles', 'work_mode',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('student_profiles', 'job_search_status')
    op.drop_column('student_profiles', 'notice_period')
    op.drop_column('student_profiles', 'preferred_industries')
    op.drop_column('student_profiles', 'preferred_work_locations')
    op.drop_column('student_profiles', 'preferred_job_roles')
    op.drop_column('student_profiles', 'personal_website')
    op.drop_column('student_profiles', 'portfolio_url')
    op.drop_column('student_profiles', 'github_url')
    op.drop_column('student_profiles', 'linkedin_url')
    op.drop_column('student_profiles', 'profile_headline')
    op.drop_column('student_profiles', 'career_status')
    op.drop_column('student_profiles', 'gender')
    op.create_unique_constraint(op.f('resumes_student_id_key'), 'resumes', ['student_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('resumes', 'visibility')
    op.drop_column('resumes', 'is_primary')
    op.drop_column('resumes', 'version')
    op.drop_column('projects', 'project_status')
    op.drop_column('projects', 'team_size')
    op.drop_column('projects', 'responsibilities')
    op.drop_column('projects', 'technologies')
    op.drop_column('projects', 'currently_active')
    op.drop_column('projects', 'project_type')
    op.add_column('experience', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('experience', 'skills_used')
    op.drop_column('experience', 'industry')
    op.drop_column('experience', 'company_location')
    op.add_column('education', sa.Column('graduation_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('education', sa.Column('field_of_study', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('education', sa.Column('start_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('education', sa.Column('grade_or_cgpa', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('education', 'grading_system')
    op.drop_column('education', 'cgpa')
    op.drop_column('education', 'percentage')
    op.drop_column('education', 'currently_studying')
    op.drop_column('education', 'end_date')
    op.drop_column('education', 'start_date')
    op.drop_column('education', 'university_or_board')
    op.drop_column('education', 'specialization')
    op.drop_column('education', 'education_level')
    # ### end Alembic commands ###
